[package]
name = "mappa-client-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mappa-client-core = { path = "../mappa-client-core" }
mappa-client-transport = { path = "../mappa-client-transport" }
mappa-device = { path = "../mappa-device" }
mappa-domain = { path = "../mappa-domain" }
mappa-protocol = { path = "../mappa-protocol" }
mappa-spatial = { path = "../mappa-spatial" }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
