[package]
name = "mappa-map-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mappa-map-core = { path = "../mappa-map-core" }
mappa-map-data = { path = "../mappa-map-data" }
wgpu = { version = "30.0.1", default-features = false, features = ["std", "metal", "wgsl"] }
lyon = "1.0.19"
geo = { version = "0.33.1", default-features = false }
bytemuck = { version = "1.25.0", features = ["derive"] }
thiserror.workspace = true
