[package]
name = "mappa-map-acquire"
default-run = "mappa-map-acquire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
md-5 = "0.11"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
sevenz-rust2 = { version = "0.23", default-features = false, features = ["util"] }
sha2 = "0.10"
tokio.workspace = true
tempfile = "3"
zip = { version = "1.1", default-features = false, features = ["deflate"] }
